title: Secure Chain
remote_theme: just-the-docs/just-the-docs@v0.6.0
logo: "/assets/securechain/logos/securechain-logo.png"
url: https://securechaindev.github.io
color_scheme: dark
color_scheme_toggle: true
aux_links:
  GitHub Organization: https://github.com/securechaindev